on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
        type: string

name: Make Release
run-name: Releasing v${{ inputs.version }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8
    - name: Install Yarn 1
      run: npm install -g yarn
    - name: Patch ASP.NET Core 8.x
      shell: pwsh
      run: ./patches/8.x/Build-PatchedBlazorWasm.ps1
    - name: Build and pack Blazor.WebAssembly.SingleSpa
      run: dotnet pack --configuration Release /p:Version=${{ inputs.version }} ./src/Blazor.WebAssembly.SingleSpa/Blazor.WebAssembly.SingleSpa.proj
    - name: Publish Blazor.WebAssembly.SingleSpa ${{ inputs.version }}
      run: dotnet nuget push ./src/Blazor.WebAssembly.SingleSpa/bin/Release/Blazor.WebAssembly.SingleSpa.${{ inputs.version }}.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_AUTH_TOKEN
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
