on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
        type: string

name: Make Release
run-name: Releasing v${{ inputs.version }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7
    - name: Install Yarn 1
      run: npm install -g yarn
    - name: Test powershell
      shell: pwsh
      run: Write-Host release ${{ inputs.version }}
