on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
        type: string

name: Make Release
run-name: Releasing v${{ inputs.version }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7
    - name: Install Yarn 1
      run: npm install -g yarn
    - name: Patch ASP.NET Core 6.x
      shell: pwsh
      run: ./patches/6.x/Build-PatchedBlazorWasm.ps1
    - name: Patch ASP.NET Core 7.x
      shell: pwsh
      run: ./patches/7.x/Build-PatchedBlazorWasm.ps1
    - name: Build and pack Blazor.WebAssembly.SingleSpa
      run: dotnet pack --configuration Release /p:Version=${{ inputs.version }} ./src/Blazor.WebAssembly.SingleSpa/Blazor.WebAssembly.SingleSpa.csproj
    - name: Test
      run: ls -la
